// <auto-generated />
using System;
using FloristAI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FloristAI.Infrastructure.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20250824133821_EditСonnectionPartnerAndUserTable")]
    partial class EditСonnectionPartnerAndUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FloristAI.Core.Entities.Items.Basket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.Items.Bouquet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Bouquets");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.Items.Flower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("Size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Flowers");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.Items.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("ProductType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.ReferralsAndPartners.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpreadsheetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.ReferralsAndPartners.PartnerReferal", b =>
                {
                    b.Property<int>("PartnerId")
                        .HasColumnType("integer");

                    b.Property<int>("ReferalId")
                        .HasColumnType("integer");

                    b.HasKey("PartnerId", "ReferalId");

                    b.HasIndex("ReferalId")
                        .IsUnique();

                    b.ToTable("PartnerReferals");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.ReferralsAndPartners.Referal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ReferalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReferalId")
                        .IsUnique();

                    b.ToTable("Referals");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.UserInfo.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.UserInfo.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Role");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.UserInfo.UserTgData", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("UserTgDatas");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.Items.Basket", b =>
                {
                    b.HasOne("FloristAI.Core.Entities.Items.Product", "Product")
                        .WithOne("Basket")
                        .HasForeignKey("FloristAI.Core.Entities.Items.Basket", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.Items.Bouquet", b =>
                {
                    b.HasOne("FloristAI.Core.Entities.Items.Product", "Product")
                        .WithOne("Bouquet")
                        .HasForeignKey("FloristAI.Core.Entities.Items.Bouquet", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.Items.Flower", b =>
                {
                    b.HasOne("FloristAI.Core.Entities.Items.Product", "Product")
                        .WithOne("Flower")
                        .HasForeignKey("FloristAI.Core.Entities.Items.Flower", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.Order", b =>
                {
                    b.HasOne("FloristAI.Core.Entities.Items.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FloristAI.Core.Entities.UserInfo.User", "User")
                        .WithMany("Order")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.ReferralsAndPartners.Partner", b =>
                {
                    b.HasOne("FloristAI.Core.Entities.UserInfo.User", "User")
                        .WithOne("Partner")
                        .HasForeignKey("FloristAI.Core.Entities.ReferralsAndPartners.Partner", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.ReferralsAndPartners.PartnerReferal", b =>
                {
                    b.HasOne("FloristAI.Core.Entities.ReferralsAndPartners.Partner", "Partner")
                        .WithMany("Partners")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FloristAI.Core.Entities.ReferralsAndPartners.Referal", "Referal")
                        .WithOne("PartnerReferal")
                        .HasForeignKey("FloristAI.Core.Entities.ReferralsAndPartners.PartnerReferal", "ReferalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");

                    b.Navigation("Referal");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.ReferralsAndPartners.Referal", b =>
                {
                    b.HasOne("FloristAI.Core.Entities.UserInfo.User", "User")
                        .WithOne("Referal")
                        .HasForeignKey("FloristAI.Core.Entities.ReferralsAndPartners.Referal", "ReferalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.Transaction", b =>
                {
                    b.HasOne("FloristAI.Core.Entities.UserInfo.User", "User")
                        .WithMany("Transaction")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.UserInfo.UserRole", b =>
                {
                    b.HasOne("FloristAI.Core.Entities.UserInfo.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.UserInfo.UserTgData", b =>
                {
                    b.HasOne("FloristAI.Core.Entities.UserInfo.User", "User")
                        .WithOne("TgData")
                        .HasForeignKey("FloristAI.Core.Entities.UserInfo.UserTgData", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.Items.Product", b =>
                {
                    b.Navigation("Basket");

                    b.Navigation("Bouquet");

                    b.Navigation("Flower");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.ReferralsAndPartners.Partner", b =>
                {
                    b.Navigation("Partners");
                });

            modelBuilder.Entity("FloristAI.Core.Entities.ReferralsAndPartners.Referal", b =>
                {
                    b.Navigation("PartnerReferal")
                        .IsRequired();
                });

            modelBuilder.Entity("FloristAI.Core.Entities.UserInfo.User", b =>
                {
                    b.Navigation("Order");

                    b.Navigation("Partner");

                    b.Navigation("Referal");

                    b.Navigation("Roles");

                    b.Navigation("TgData");

                    b.Navigation("Transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
